In [1]:
import pya
import numpy as np




In [2]:
a =1
a

1

In [89]:

#initialize
layout = pya.Layout()
top = layout.create_cell('top')



# single_calibration = layout.create_cell('rectangle')
# layer_n = layout.layer("layer_n")


layers = np.arange(0,128)




# Create matrix of squares for measurement
cell_gs_matrix = layout.create_cell('gs_matrix')

step = 50.0
square_side = 30

rows = range(8)
cols = range(16)

CC,RR = np.meshgrid(cols, rows, indexing='xy')

for i, (layer, col, row) in enumerate(zip(layers, CC.flatten(), RR.flatten())):
    # print(i, layer, row, col)
    layer_name = "layer%03d"%(layer)

    layer_i = layout.layer(layer_name)

    x,y = step*col, -step*row

    # print(x,y, x+square_side, y+square_side)


    # new_instance = pya.CellInstArray(cell_single_level.cell_index(), trans, pya.Vector(50, 0 ), pya.Vector(0, 50), 16, 8 )
    # cell_single_level.shapes(layer_i).insert(pya.Box(square_side, square_side).move(pya.Vector(dx, dy)))
    # cell_single_level.shapes(layer_i).insert(pya.DBox(square_side, square_side))
    cell_gs_matrix.shapes(layer_i).insert(pya.DBox(x,y, x+square_side, y+square_side))

trans = pya.Trans(pya.Point(0,0))

new_instance = pya.DCellInstArray(cell_gs_matrix.cell_index(), trans, pya.Vector(50, 0 ), pya.Vector(0, 50), 1,1)
# reference cell index, transformation, x offset, y offset, number of x instances, and number of y instances

# calibration_instance = pya.Instance()
top.insert(new_instance)

total_width = 780



## Create the and decreasing increasing GS ramps
cell_ramps = layout.create_cell('gs_ramps')


ramp_width = 5
ramp_height = 50
step_gs = ramp_width

x_position = 70.0
y_position = 50.0

# decreasing_ramp:
for i, (layer) in enumerate(layers):

    layer_name = "layer%03d"%(layer)

    layer_i = layout.layer(layer_name)
    x,y = x_position+step_gs*i, y_position+ 0

    cell_ramps.shapes(layer_i).insert(pya.DBox(x,y, x+ramp_width, y+ramp_height))

# add start and ending squares
layer_i = layout.layer("layer%03d"%(127))
cell_ramps.shapes(layer_i).insert(pya.DBox(0, y_position, 60, y_position+ramp_height))
cell_ramps.shapes(layer_i).insert(pya.DBox(total_width-60.0,y_position, total_width, y_position+ramp_height))

trans = pya.Trans(pya.Point(x_position,y_position))
trans = pya.Trans(pya.Point(0,0))

new_instance = pya.DCellInstArray(cell_ramps.cell_index(), trans, pya.Vector(50, 0 ), pya.Vector(0, 50), 1,1)

top.insert(new_instance)



## Create the increasing and decreasing increasing GS ramps
cell_triangle = layout.create_cell('gs_triangle]')



ramp_width = 2
ramp_height = 50
step_gs = ramp_width

x_position = (780-ramp_width*len(layers)*2)/2
y_position = 120.0

y_position2 = 190
x_position2 = total_width/2

end_x_position = x_position+ramp_width*len(layers)*2

# decreasing_ramp:
for i, (layer) in enumerate(layers):

    layer_name = "layer%03d"%(layer)

    layer_i = layout.layer(layer_name)
    x,y = x_position+step_gs*i, y_position+ 0

    cell_triangle.shapes(layer_i).insert(pya.DBox(x,y, x+ramp_width, y+ramp_height))
    
    x,y = end_x_position-(step_gs*(i+1)), y_position+ 0
    print(x)
    cell_triangle.shapes(layer_i).insert(pya.DBox(x,y, x+ramp_width, y+ramp_height))

    # increasing
    x,y = x_position2+step_gs*i, y_position2+ 0

    cell_triangle.shapes(layer_i).insert(pya.DBox(x,y, x+ramp_width, y+ramp_height))
    
    x,y = x_position2-(step_gs*(i+1)), y_position2+ 0
    
    cell_triangle.shapes(layer_i).insert(pya.DBox(x,y, x+ramp_width, y+ramp_height))



# add start and ending squares
layer_i = layout.layer("layer%03d"%(127))
cell_triangle.shapes(layer_i).insert(pya.DBox(0, y_position, 100, y_position+ramp_height))
cell_triangle.shapes(layer_i).insert(pya.DBox(total_width-100.0,y_position, total_width, y_position+ramp_height))


cell_triangle.shapes(layer_i).insert(pya.DBox(0, y_position2, 100, y_position2+ramp_height))
cell_triangle.shapes(layer_i).insert(pya.DBox(total_width-100.0,y_position2, total_width, y_position2+ramp_height))

trans = pya.Trans(pya.Point(x_position,y_position))
trans = pya.Trans(pya.Point(0,0))

new_instance = pya.DCellInstArray(cell_triangle.cell_index(), trans, pya.Vector(50, 0 ), pya.Vector(0, 50), 1,1)


top.insert(new_instance)





total_width = 780



## Create the and decreasing increasing GS ramps
cell_ramps = layout.create_cell('gs_ramps_1um')


ramp_width = 1
ramp_height = 50
step_gs = ramp_width

x_position = 170.0
x_position = (780-ramp_width*len(layers))/2

y_position = 260.0

# decreasing_ramp:
for i, (layer) in enumerate(layers):

    layer_name = "layer%03d"%(layer)

    layer_i = layout.layer(layer_name)
    x,y = x_position+step_gs*i, y_position+ 0

    cell_ramps.shapes(layer_i).insert(pya.DBox(x,y, x+ramp_width, y+ramp_height))

# add start and ending squares
layer_i = layout.layer("layer%03d"%(127))
cell_ramps.shapes(layer_i).insert(pya.DBox(0, y_position, 60, y_position+ramp_height))
cell_ramps.shapes(layer_i).insert(pya.DBox(total_width-60.0,y_position, total_width, y_position+ramp_height))

trans = pya.Trans(pya.Point(x_position,y_position))
trans = pya.Trans(pya.Point(0,0))

new_instance = pya.DCellInstArray(cell_ramps.cell_index(), trans, pya.Vector(50, 0 ), pya.Vector(0, 50), 1,1)

top.insert(new_instance)

## Create the and decreasing increasing GS ramps
cell_ramps = layout.create_cell('gs_ramps_1um_clear_1um')


ramp_width = 1
ramp_height = 50
step_gs = ramp_width+1

x_position = 170.0
x_position = (780-step_gs*len(layers))/2

y_position = 330.0

# decreasing_ramp:
for i, (layer) in enumerate(layers):

    layer_name = "layer%03d"%(layer)

    layer_i = layout.layer(layer_name)
    x,y = x_position+step_gs*i, y_position+ 0

    cell_ramps.shapes(layer_i).insert(pya.DBox(x,y, x+ramp_width, y+ramp_height))

# add start and ending squares
layer_i = layout.layer("layer%03d"%(127))
cell_ramps.shapes(layer_i).insert(pya.DBox(0, y_position, 60, y_position+ramp_height))
cell_ramps.shapes(layer_i).insert(pya.DBox(total_width-60.0,y_position, total_width, y_position+ramp_height))

trans = pya.Trans(pya.Point(x_position,y_position))
trans = pya.Trans(pya.Point(0,0))

new_instance = pya.DCellInstArray(cell_ramps.cell_index(), trans, pya.Vector(50, 0 ), pya.Vector(0, 50), 1,1)

top.insert(new_instance)







# Create matrix of squares of random meausrmeents for measurement
cell_gs_matrix = layout.create_cell('gs_matrix_1um')

x_position = 170.0
x_position = (780-step_gs*len(layers))/2

# add start and ending squares

start_height = 30

y_position = 400
layer_i = layout.layer("layer%03d"%(127))
cell_gs_matrix.shapes(layer_i).insert(pya.DBox(0, y_position, 60, y_position+start_height))
cell_gs_matrix.shapes(layer_i).insert(pya.DBox(total_width-60.0,y_position, total_width, y_position+start_height))

y_matrix_position = y_position+start_height



x_matrix_position = 100.0
step = 1.0
square_side = 1
rows = range(8)
cols = range(16)
CC,RR = np.meshgrid(cols, rows, indexing='xy')
for i, (layer, col, row) in enumerate(zip(layers, CC.flatten(), RR.flatten())):
    # print(i, layer, row, col)
    layer_name = "layer%03d"%(layer)
    layer_i = layout.layer(layer_name)
    x,y = x_matrix_position+step*col, -step*row+y_matrix_position
    cell_gs_matrix.shapes(layer_i).insert(pya.DBox(x,y, x+square_side, y+square_side))
trans = pya.Trans(pya.Point(0,0))
new_instance = pya.DCellInstArray(cell_gs_matrix.cell_index(), trans, pya.Vector(50, 0 ), pya.Vector(0, 50), 1,1)


x_matrix_position = 150.0
step = 2.0
square_side = 1
rows = range(8)
cols = range(16)
CC,RR = np.meshgrid(cols, rows, indexing='xy')
for i, (layer, col, row) in enumerate(zip(layers, CC.flatten(), RR.flatten())):
    # print(i, layer, row, col)
    layer_name = "layer%03d"%(layer)
    layer_i = layout.layer(layer_name)
    x,y = x_matrix_position+step*col, -step*row+y_matrix_position
    cell_gs_matrix.shapes(layer_i).insert(pya.DBox(x,y, x+square_side, y+square_side))
trans = pya.Trans(pya.Point(0,0))
new_instance = pya.DCellInstArray(cell_gs_matrix.cell_index(), trans, pya.Vector(50, 0 ), pya.Vector(0, 50), 1,1)


x_matrix_position = 200.0
step = 2.0
square_side = 2
rows = range(8)
cols = range(16)
CC,RR = np.meshgrid(cols, rows, indexing='xy')
for i, (layer, col, row) in enumerate(zip(layers, CC.flatten(), RR.flatten())):
    # print(i, layer, row, col)
    layer_name = "layer%03d"%(layer)
    layer_i = layout.layer(layer_name)
    x,y = x_matrix_position+step*col, -step*row+y_matrix_position
    cell_gs_matrix.shapes(layer_i).insert(pya.DBox(x,y, x+square_side, y+square_side))
trans = pya.Trans(pya.Point(0,0))
new_instance = pya.DCellInstArray(cell_gs_matrix.cell_index(), trans, pya.Vector(50, 0 ), pya.Vector(0, 50), 1,1)


x_matrix_position = 250.0
step = 3.0
square_side = 2
rows = range(8)
cols = range(16)
CC,RR = np.meshgrid(cols, rows, indexing='xy')
for i, (layer, col, row) in enumerate(zip(layers, CC.flatten(), RR.flatten())):
    # print(i, layer, row, col)
    layer_name = "layer%03d"%(layer)
    layer_i = layout.layer(layer_name)
    x,y = x_matrix_position+step*col, -step*row+y_matrix_position
    cell_gs_matrix.shapes(layer_i).insert(pya.DBox(x,y, x+square_side, y+square_side))
trans = pya.Trans(pya.Point(0,0))
new_instance = pya.DCellInstArray(cell_gs_matrix.cell_index(), trans, pya.Vector(50, 0 ), pya.Vector(0, 50), 1,1)


x_matrix_position = 320.0
step = 3.0
square_side = 3
rows = range(8)
cols = range(16)
CC,RR = np.meshgrid(cols, rows, indexing='xy')
for i, (layer, col, row) in enumerate(zip(layers, CC.flatten(), RR.flatten())):
    # print(i, layer, row, col)
    layer_name = "layer%03d"%(layer)
    layer_i = layout.layer(layer_name)
    x,y = x_matrix_position+step*col, -step*row+y_matrix_position
    cell_gs_matrix.shapes(layer_i).insert(pya.DBox(x,y, x+square_side, y+square_side))
trans = pya.Trans(pya.Point(0,0))
new_instance = pya.DCellInstArray(cell_gs_matrix.cell_index(), trans, pya.Vector(50, 0 ), pya.Vector(0, 50), 1,1)


top.insert(new_instance)


##################################################################
# =--=----
# Create matrix of squares for measurement of random
cell_gs_matrix = layout.create_cell('gs_matrix_1um_random')


# Set the seed for reproducibility
np.random.seed(42)

# Create the array
arr = np.random.randint(0, 128, size=(8,16))


x_position = 170.0
x_position = (780-step_gs*len(layers))/2

# add start and ending squares

start_height = 30

y_position = 435
layer_i = layout.layer("layer%03d"%(127))
cell_gs_matrix.shapes(layer_i).insert(pya.DBox(0, y_position, 60, y_position+start_height))
cell_gs_matrix.shapes(layer_i).insert(pya.DBox(total_width-60.0,y_position, total_width, y_position+start_height))

y_matrix_position = y_position+start_height



x_matrix_position = 100.0
step = 1.0
square_side = 1
rows = range(8)
cols = range(16)
CC,RR = np.meshgrid(cols, rows, indexing='xy')
for i, (layer, col, row) in enumerate(zip(layers, CC.flatten(), RR.flatten())):
    # print(i, layer, row, col)

    layer = arr[row, col]
    layer_name = "layer%03d"%(layer)
    layer_i = layout.layer(layer_name)
    x,y = x_matrix_position+step*col, -step*row+y_matrix_position
    cell_gs_matrix.shapes(layer_i).insert(pya.DBox(x,y, x+square_side, y+square_side))
trans = pya.Trans(pya.Point(0,0))
new_instance = pya.DCellInstArray(cell_gs_matrix.cell_index(), trans, pya.Vector(50, 0 ), pya.Vector(0, 50), 1,1)


x_matrix_position = 150.0
step = 2.0
square_side = 1
rows = range(8)
cols = range(16)
CC,RR = np.meshgrid(cols, rows, indexing='xy')
for i, (layer, col, row) in enumerate(zip(layers, CC.flatten(), RR.flatten())):
    # print(i, layer, row, col)
    layer = arr[row, col]
    layer_name = "layer%03d"%(layer)
    layer_i = layout.layer(layer_name)
    x,y = x_matrix_position+step*col, -step*row+y_matrix_position
    cell_gs_matrix.shapes(layer_i).insert(pya.DBox(x,y, x+square_side, y+square_side))
trans = pya.Trans(pya.Point(0,0))
new_instance = pya.DCellInstArray(cell_gs_matrix.cell_index(), trans, pya.Vector(50, 0 ), pya.Vector(0, 50), 1,1)


x_matrix_position = 200.0
step = 2.0
square_side = 2
rows = range(8)
cols = range(16)
CC,RR = np.meshgrid(cols, rows, indexing='xy')
for i, (layer, col, row) in enumerate(zip(layers, CC.flatten(), RR.flatten())):
    # print(i, layer, row, col)
    layer = arr[row, col]
    layer_name = "layer%03d"%(layer)
    layer_i = layout.layer(layer_name)
    x,y = x_matrix_position+step*col, -step*row+y_matrix_position
    cell_gs_matrix.shapes(layer_i).insert(pya.DBox(x,y, x+square_side, y+square_side))
trans = pya.Trans(pya.Point(0,0))
new_instance = pya.DCellInstArray(cell_gs_matrix.cell_index(), trans, pya.Vector(50, 0 ), pya.Vector(0, 50), 1,1)


x_matrix_position = 250.0
step = 3.0
square_side = 2
rows = range(8)
cols = range(16)
CC,RR = np.meshgrid(cols, rows, indexing='xy')
for i, (layer, col, row) in enumerate(zip(layers, CC.flatten(), RR.flatten())):
    # print(i, layer, row, col)
    layer = arr[row, col]
    layer_name = "layer%03d"%(layer)
    layer_i = layout.layer(layer_name)
    x,y = x_matrix_position+step*col, -step*row+y_matrix_position
    cell_gs_matrix.shapes(layer_i).insert(pya.DBox(x,y, x+square_side, y+square_side))
trans = pya.Trans(pya.Point(0,0))
new_instance = pya.DCellInstArray(cell_gs_matrix.cell_index(), trans, pya.Vector(50, 0 ), pya.Vector(0, 50), 1,1)


x_matrix_position = 320.0
step = 3.0
square_side = 3
rows = range(8)
cols = range(16)
CC,RR = np.meshgrid(cols, rows, indexing='xy')
for i, (layer, col, row) in enumerate(zip(layers, CC.flatten(), RR.flatten())):
    # print(i, layer, row, col)
    layer = arr[row, col]
    layer_name = "layer%03d"%(layer)
    layer_i = layout.layer(layer_name)
    x,y = x_matrix_position+step*col, -step*row+y_matrix_position
    cell_gs_matrix.shapes(layer_i).insert(pya.DBox(x,y, x+square_side, y+square_side))
trans = pya.Trans(pya.Point(0,0))
new_instance = pya.DCellInstArray(cell_gs_matrix.cell_index(), trans, pya.Vector(50, 0 ), pya.Vector(0, 50), 1,1)

top.insert(new_instance)








##############################################################################
##############################################################################
##############################################################################


## Create the and decreasing increasing GS ramps
cell_ramps = layout.create_cell('gs_slopes_sublayers_1um')


ramp_width = 1
ramp_height = 50
step_gs = ramp_width


y_position = 480.0

x_position = 100.0
# x_position = (780-step_gs*len(layers))/2

start_gl = 0

for i in [1,2,3,4,5,6,7,8]:
    sublayers = np.arange(start_gl,128,i)
    # decreasing_ramp:
    for i, (layer) in enumerate(sublayers):

        layer_name = "layer%03d"%(layer)

        layer_i = layout.layer(layer_name)
        x,y = x_position+step_gs*i, y_position+ 0

        cell_ramps.shapes(layer_i).insert(pya.DBox(x,y, x+ramp_width, y+ramp_height))


    x_position = x+ramp_width+30


# add start and ending squares
layer_i = layout.layer("layer%03d"%(127))
cell_ramps.shapes(layer_i).insert(pya.DBox(0, y_position, 60, y_position+ramp_height))
cell_ramps.shapes(layer_i).insert(pya.DBox(total_width-60.0,y_position, total_width, y_position+ramp_height))

y_position += 70

x_position = 100.0
# x_position = (780-step_gs*len(layers))/2


for i in [9,10,11,12,13,14,15,16,17,18,19,20,21,22,23]:
    sublayers = np.arange(start_gl,128,i)
    # decreasing_ramp:
    for i, (layer) in enumerate(sublayers):

        layer_name = "layer%03d"%(layer)

        layer_i = layout.layer(layer_name)
        x,y = x_position+step_gs*i, y_position+ 0

        cell_ramps.shapes(layer_i).insert(pya.DBox(x,y, x+ramp_width, y+ramp_height))


    x_position = x+ramp_width+30

# add start and ending squares
layer_i = layout.layer("layer%03d"%(127))
cell_ramps.shapes(layer_i).insert(pya.DBox(0, y_position, 60, y_position+ramp_height))
cell_ramps.shapes(layer_i).insert(pya.DBox(total_width-60.0,y_position, total_width, y_position+ramp_height))

y_position += 70

x_position = 100.0
# x_position = (780-step_gs*len(layers))/2


for i in [24,25,26,27,28,29,30,31,32,64,127]:
    sublayers = np.arange(start_gl,128,i)
    # decreasing_ramp:
    for i, (layer) in enumerate(sublayers):

        layer_name = "layer%03d"%(layer)

        layer_i = layout.layer(layer_name)
        x,y = x_position+step_gs*i, y_position+ 0

        cell_ramps.shapes(layer_i).insert(pya.DBox(x,y, x+ramp_width, y+ramp_height))


    x_position = x+ramp_width+30

# add start and ending squares
layer_i = layout.layer("layer%03d"%(127))
cell_ramps.shapes(layer_i).insert(pya.DBox(0, y_position, 60, y_position+ramp_height))
cell_ramps.shapes(layer_i).insert(pya.DBox(total_width-60.0,y_position, total_width, y_position+ramp_height))

trans = pya.Trans(pya.Point(x_position,y_position))
trans = pya.Trans(pya.Point(0,0))

new_instance = pya.DCellInstArray(cell_ramps.cell_index(), trans, pya.Vector(50, 0 ), pya.Vector(0, 50), 1,1)

top.insert(new_instance)


# ##############################################################################
# ##############################################################################
# ##############################################################################


# ## Create the and decreasing increasing GS ramps
# cell_ramps = layout.create_cell('gs_ramps_sublayers_1um')


# ramp_width = 1
# ramp_height = 50
# step_gs = ramp_width


# y_position = 550.0

# x_position = 100.0
# # x_position = (780-step_gs*len(layers))/2

# sublayers = np.arange(0,128,1)

# start_layer = 0
# step_layers = 1
# N_layers = 10

# sublayers = np.arange(start_layer,start_layer+N_layers,step_layers)

# # decreasing_ramp:
# for i, (layer) in enumerate(sublayers):

#     layer_name = "layer%03d"%(layer)

#     layer_i = layout.layer(layer_name)
#     x,y = x_position+step_gs*i, y_position+ 0

#     cell_ramps.shapes(layer_i).insert(pya.DBox(x,y, x+ramp_width, y+ramp_height))


# x_position = x_position+150.0
# # x_position = (780-step_gs*len(layers))/2


# # add start and ending squares
# layer_i = layout.layer("layer%03d"%(127))
# cell_ramps.shapes(layer_i).insert(pya.DBox(0, y_position, 60, y_position+ramp_height))
# cell_ramps.shapes(layer_i).insert(pya.DBox(total_width-60.0,y_position, total_width, y_position+ramp_height))

# trans = pya.Trans(pya.Point(x_position,y_position))
# trans = pya.Trans(pya.Point(0,0))

# new_instance = pya.DCellInstArray(cell_ramps.cell_index(), trans, pya.Vector(50, 0 ), pya.Vector(0, 50), 1,1)

# top.insert(new_instance)


# calibration_instance = pya.Instance()





layout.write("test.dxf")



layout.write("gs_calibration_v20240507.dxf")

644.0
642.0
640.0
638.0
636.0
634.0
632.0
630.0
628.0
626.0
624.0
622.0
620.0
618.0
616.0
614.0
612.0
610.0
608.0
606.0
604.0
602.0
600.0
598.0
596.0
594.0
592.0
590.0
588.0
586.0
584.0
582.0
580.0
578.0
576.0
574.0
572.0
570.0
568.0
566.0
564.0
562.0
560.0
558.0
556.0
554.0
552.0
550.0
548.0
546.0
544.0
542.0
540.0
538.0
536.0
534.0
532.0
530.0
528.0
526.0
524.0
522.0
520.0
518.0
516.0
514.0
512.0
510.0
508.0
506.0
504.0
502.0
500.0
498.0
496.0
494.0
492.0
490.0
488.0
486.0
484.0
482.0
480.0
478.0
476.0
474.0
472.0
470.0
468.0
466.0
464.0
462.0
460.0
458.0
456.0
454.0
452.0
450.0
448.0
446.0
444.0
442.0
440.0
438.0
436.0
434.0
432.0
430.0
428.0
426.0
424.0
422.0
420.0
418.0
416.0
414.0
412.0
410.0
408.0
406.0
404.0
402.0
400.0
398.0
396.0
394.0
392.0
390.0


In [34]:
import numpy as np

# Set the seed for reproducibility
np.random.seed(42)

# Create the array
arr = np.random.randint(0, 128, size=(8,16))

# Print the array
print(arr)


[[102  51  92  14 106  71  60  20 102 121  82  86  74  74  87 116]
 [ 99 103  23   2  21  52   1  87 107  29  37   1  63  59  20  32]
 [ 75  57  21 124 107  88  48  90  58 126  41 127  91  59  79  14]
 [ 61  61  46  61  50 107  54 115  63 120   2 100  50   6  20  72]
 [ 38  17   3  88  59  13 113 121   8  89  52   1  83  91 110  59]
 [ 70  43 124   7  46  34  77  80  35  49 103   3   1 125   5  53]
 [105   3  53  92  62  17  89  43  33  73  61  99  13  94  47  14]
 [ 71  77  86 123 120  61  39  84  79 108  81 110  52  23  25  88]]


In [ ]:
1.4 um com 10 niveis




a = np.array( [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,64,127,])


In [5]:
94/128 /0.8*128

117.5

In [12]:
import numpy as np
a = np.array( [1,2,3,4,5,6,7,8,   9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,   24,25,26,27,28,29,30,31,32,64,127,])
target_slope = 1.4/10

thickness = 2.465

slope = thickness/117



slope, target_slope

minidx = np.argmin(abs(slope*a-target_slope))
a[minidx]


7

In [15]:
slope*a, target, slope*a-target_slope

(array([0.02106838, 0.04213675, 0.06320513, 0.0842735 , 0.10534188,
        0.12641026, 0.14747863, 0.16854701, 0.18961538, 0.21068376,
        0.23175214, 0.25282051, 0.27388889, 0.29495726, 0.31602564,
        0.33709402, 0.35816239, 0.37923077, 0.40029915, 0.42136752,
        0.4424359 , 0.46350427, 0.48457265, 0.50564103, 0.5267094 ,
        0.54777778, 0.56884615, 0.58991453, 0.61098291, 0.63205128,
        0.65311966, 0.67418803, 1.34837607, 2.67568376]),
 0.13999999999999999,
 array([-0.11893162, -0.09786325, -0.07679487, -0.0557265 , -0.03465812,
        -0.01358974,  0.00747863,  0.02854701,  0.04961538,  0.07068376,
         0.09175214,  0.11282051,  0.13388889,  0.15495726,  0.17602564,
         0.19709402,  0.21816239,  0.23923077,  0.26029915,  0.28136752,
         0.3024359 ,  0.32350427,  0.34457265,  0.36564103,  0.3867094 ,
         0.40777778,  0.42884615,  0.44991453,  0.47098291,  0.49205128,
         0.51311966,  0.53418803,  1.20837607,  2.53568376]))

In [ ]:

#initialize
layout = pya.Layout()
top = layout.create_cell('top')
c_circle = layout.create_cell('circle')
l_circle = layout.layer("layer000")

# make a circle pcell
radius = 200 #radius in nm
nr_points = 32 #number of points
#create an array of angles
angles = np.linspace(0,2*np.pi,nr_points+1)[0:-1]
points = [] #array of point
for angle in angles:
    points.append(pya.Point(radius*np.cos(angle),radius*np.sin(angle)))
circle = pya.SimplePolygon(points)



#for hexagonal grid
a = 400 #hexagon radius towards flat
#number of instances
i=10
c_circle.shapes(l_circle).insert(circle)
c_circle.shapes(l_circle).insert(circle.moved(a*np.sqrt(3),a))



trans = pya.Trans(pya.Point(0,0))
new_instance = pya.CellInstArray(c_circle.cell_index(),trans,pya.Vector(2*a*np.sqrt(3), 0 ), pya.Vector(0, 2*a), i/2, i/2)
top.insert(new_instance)
layout.write("test.dxf")